name: Lint protos

on:
  pull_request:
    branches: [v1]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: v1

      - name: Setup build.buf
        uses: bufbuild/buf-setup-action@v1.1.0
        with:
          version: 1.1.0

      - name: Lint protos
        run: make lint
